<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Programa;
use Illuminate\Support\Str;

class ProgramaSeeder extends Seeder
{
    public function run(): void
    {
        $programas = [
            // MAESTRÍAS
            [
                'codigo' => 'M-LIT',
                'grado' => 'Maestría',
                'nombre' => 'Literatura Peruana y Latinoamericana',
                'mencion' => null,
                'modalidad' => 'Presencial',
                'vacantes' => 25,
                'duracion' => 4,
                'creditos' => 48,
                'grado_otorga_label' => 'Grado que otorga',
                'grado_otorga' => 'Magíster en Literatura Peruana y Latinoamericana',
                'plan_url' => null,
                'por_que_text' => 'Programa orientado al estudio crítico de la literatura peruana y latinoamericana.',
                'presentacion' => 'La Maestría en Literatura Peruana y Latinoamericana forma investigadores especializados en el análisis crítico de la producción literaria de la región.',
                'sumilla' => 'Formación especializada en literatura peruana y latinoamericana con enfoque crítico e investigativo.',
                'descripcion' => 'Programa de posgrado que profundiza en el estudio de la literatura peruana y latinoamericana desde perspectivas teóricas contemporáneas.',
                'perfil_egresado' => 'El egresado será capaz de realizar investigación literaria de alto nivel y contribuir al desarrollo de los estudios literarios.',
                'plan_estudios' => null,
                'is_active' => true,
                'imagen' => asset('images/programas/literatura.jpg'),
            ],
            [
                'codigo' => 'M-LING',
                'grado' => 'Maestría',
                'nombre' => 'Lingüística',
                'mencion' => null,
                'modalidad' => 'Presencial',
                'vacantes' => 20,
                'duracion' => 4,
                'creditos' => 48,
                'grado_otorga_label' => 'Grado que otorga',
                'grado_otorga' => 'Magíster en Lingüística',
                'plan_url' => null,
                'por_que_text' => 'Programa dedicado al estudio científico del lenguaje y sus aplicaciones.',
                'presentacion' => 'La Maestría en Lingüística ofrece formación avanzada en teoría lingüística y metodología de investigación.',
                'sumilla' => 'Formación especializada en lingüística teórica y aplicada.',
                'descripcion' => 'Programa que aborda el estudio del lenguaje desde perspectivas teóricas y aplicadas contemporáneas.',
                'perfil_egresado' => 'Investigador capaz de analizar fenómenos lingüísticos y contribuir al desarrollo de la disciplina.',
                'plan_estudios' => null,
                'is_active' => true,
                'imagen' => asset('images/programas/linguistica.jpg'),
            ],
            [
                'codigo' => 'M-FIL',
                'grado' => 'Maestría',
                'nombre' => 'Filosofía',
                'mencion' => 'Epistemología',
                'modalidad' => 'Presencial',
                'vacantes' => 15,
                'duracion' => 4,
                'creditos' => 48,
                'grado_otorga_label' => 'Grado que otorga',
                'grado_otorga' => 'Magíster en Filosofía con mención en Epistemología',
                'plan_url' => null,
                'por_que_text' => 'Programa enfocado en el estudio de la teoría del conocimiento.',
                'presentacion' => 'La Maestría en Filosofía con mención en Epistemología profundiza en las teorías del conocimiento.',
                'sumilla' => 'Formación especializada en epistemología y filosofía del conocimiento.',
                'descripcion' => 'Programa que aborda las principales corrientes epistemológicas contemporáneas.',
                'perfil_egresado' => 'Filósofo investigador especializado en teoría del conocimiento.',
                'plan_estudios' => null,
                'is_active' => true,
                'imagen' => asset('images/programas/filosofia.jpg'),
            ],
            [
                'codigo' => 'M-COM',
                'grado' => 'Maestría',
                'nombre' => 'Comunicación Social',
                'mencion' => null,
                'modalidad' => 'Presencial',
                'vacantes' => 30,
                'duracion' => 4,
                'creditos' => 48,
                'grado_otorga_label' => 'Grado que otorga',
                'grado_otorga' => 'Magíster en Comunicación Social',
                'plan_url' => null,
                'por_que_text' => 'Programa orientado al estudio de los procesos comunicacionales.',
                'presentacion' => 'La Maestría en Comunicación Social forma investigadores en comunicación y medios.',
                'sumilla' => 'Formación especializada en comunicación social y medios.',
                'descripcion' => 'Programa que analiza los fenómenos comunicacionales desde perspectivas críticas.',
                'perfil_egresado' => 'Investigador en comunicación capaz de analizar procesos mediáticos.',
                'plan_estudios' => null,
                'is_active' => true,
                'imagen' => asset('images/programas/comunicacion.jpg'),
            ],

            // DOCTORADOS
            [
                'codigo' => 'D-LIT',
                'grado' => 'Doctorado',
                'nombre' => 'Literatura Peruana y Latinoamericana',
                'mencion' => null,
                'modalidad' => 'Presencial',
                'vacantes' => 15,
                'duracion' => 6,
                'creditos' => 64,
                'grado_otorga_label' => 'Grado que otorga',
                'grado_otorga' => 'Doctor en Literatura Peruana y Latinoamericana',
                'plan_url' => null,
                'por_que_text' => 'Programa doctoral de excelencia en estudios literarios.',
                'presentacion' => 'El Doctorado en Literatura forma investigadores de alto nivel en estudios literarios.',
                'sumilla' => 'Formación doctoral en investigación literaria de excelencia.',
                'descripcion' => 'Programa doctoral que forma investigadores capaces de generar conocimiento original en literatura.',
                'perfil_egresado' => 'Doctor investigador con capacidad de producir conocimiento original en literatura.',
                'plan_estudios' => null,
                'is_active' => true,
                'imagen' => asset('images/programas/doctorado-literatura.jpg'),
            ],
            [
                'codigo' => 'D-LING',
                'grado' => 'Doctorado',
                'nombre' => 'Lingüística',
                'mencion' => null,
                'modalidad' => 'Presencial',
                'vacantes' => 12,
                'duracion' => 6,
                'creditos' => 64,
                'grado_otorga_label' => 'Grado que otorga',
                'grado_otorga' => 'Doctor en Lingüística',
                'plan_url' => null,
                'por_que_text' => 'Programa doctoral de excelencia en lingüística.',
                'presentacion' => 'El Doctorado en Lingüística forma investigadores de alto nivel en ciencias del lenguaje.',
                'sumilla' => 'Formación doctoral en investigación lingüística de excelencia.',
                'descripcion' => 'Programa doctoral que forma investigadores capaces de generar conocimiento original en lingüística.',
                'perfil_egresado' => 'Doctor investigador con capacidad de producir conocimiento original en lingüística.',
                'plan_estudios' => null,
                'is_active' => true,
                'imagen' => asset('images/programas/doctorado-linguistica.jpg'),
            ],
            [
                'codigo' => 'D-FIL',
                'grado' => 'Doctorado',
                'nombre' => 'Filosofía',
                'mencion' => null,
                'modalidad' => 'Presencial',
                'vacantes' => 10,
                'duracion' => 6,
                'creditos' => 64,
                'grado_otorga_label' => 'Grado que otorga',
                'grado_otorga' => 'Doctor en Filosofía',
                'plan_url' => null,
                'por_que_text' => 'Programa doctoral de excelencia en filosofía.',
                'presentacion' => 'El Doctorado en Filosofía forma investigadores de alto nivel en pensamiento filosófico.',
                'sumilla' => 'Formación doctoral en investigación filosófica de excelencia.',
                'descripcion' => 'Programa doctoral que forma investigadores capaces de generar conocimiento original en filosofía.',
                'perfil_egresado' => 'Doctor investigador con capacidad de producir conocimiento original en filosofía.',
                'plan_estudios' => null,
                'is_active' => true,
                'imagen' => asset('images/programas/doctorado-filosofia.jpg'),
            ],
        ];

        foreach ($programas as $programa) {
            Programa::create($programa);
        }
    }
}
